version: "3"
services:
  app:
    build: ./app
    environment:
      - DEBUG=app
      # ソースコードをnodemonにネットワーク越しに監視させる
      - CHOKIDAR_USEPOLLING=1
    tty: true
    working_dir: /src
    volumes:
      - ./app:/src
    ports:
      - "3000:3000"
    command: npm run dev
  db:
    image: mysql:5.7.34
    command: mysqld --character-set-server=utf8mb4
    environment:
      MYSQL_ROOT_PASSWORD: "mysqlrootpass"
      MYSQL_DATABASE: "sample01"
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apipasswd
    volumes:
      - ./db/db-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    restart: always
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: "1"
      PMA_HOST: "db"
      PMA_USER: apiuser
      PMA_PASSWORD: apipasswd
