version: "3"
services:
  app:
#    build: app/
    image: node:lts
    environment:
      - DEBUG=app
      # nodemonにネットワーク越しに監視させる
      - CHOKIDAR_USEPOLLING=1
    tty: true
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
